---
- name: update ca-cert package and restart the service
  hosts: all
  become: yes
  vars_files:
    - as_vars.yml
#    - as_vmware_vars.yml
  tasks:
    - name: update ca-certifications
      package:
        name: ca-certifications
        state: latest
      notify:
      - do the update

    - name: do the update
      command: update-ca-trust force-enable
#      listen: "update ca-certification"