---
- name: IF ILLUMIO VEN IS NOT INSTALLED, CHECK PREREQUISITES AND INSTALL
  hosts: all
  become: yes
  vars_files:
    - as_vars.yml
#    - as_vmware_vars.yml
  tasks:
    - name: update ca-certifications
      package:
        name: ca-certifications
        state: latest
      notify:
      - Update ca-trust

    - name: Update ca-trust
      command: update-ca-trust force-enable
      listen: "update ca-certification"