---
#
#
# CAUTION: This playbook just force-feeds the "unpair" directive to the illumio-ven-ctl agent interface, without doing 
#          any error checking; it really should have some sort of pre- and post-checks added.
# 
# USE AT YOUR OWN RISK
#
- name: unpair Illumio VEN
  hosts: all
  become: yes
  vars_files:
    - as_vars.yml
#    - as_vmware_vars.yml

  tasks:

    - name: deactivate VEN
      command: /opt/illumio_ven/illumio-ven-ctl deactivate
      ignore_errors: True

    - name: umpair VEN and restore save IP filtering state
      command: /opt/illumio_ven/illumio-ven-ctl unpair saved
      ignore_errors: True

    - name: remove the onboarding script
      file:
        state: absent
        path: /export/home/mnottage/onboarding.sh

    - name: Delete content & directory
      file:
        state: absent
        path: /opt/illumio_ven/
